version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: deepfake-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QWERTY
      POSTGRES_DB: deepfake_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - deepfake-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 20s
      retries: 10

volumes:
  postgres_data:

networks:
  deepfake-network:
    driver: bridge
